apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-lifx-web-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: lifx-web-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: lifx-web-controller
    spec:
      containers:
        - name: lifx-web-controller
          image: gregorymichaelroman/sample-app:latest
          ports:
            - containerPort: 3000
