apiVersion: v1
kind: Service
metadata:
  name: svc-lifx-web-controller
  labels:
    app.kubernetes.io/name: lifx-web-controller
spec:
  type: LoadBalancer
  ports:
    - port: 9000 # Exposed Port
      targetPort: 3000 # Application Port
      protocol: TCP
  selector:
    app.kubernetes.io/name: lifx-web-controller
