apiVersion: v1
kind: Service
metadata:
  name: svc-roku-remote
  labels:
    app.kubernetes.io/name: roku-remote
spec:
  type: LoadBalancer
  ports:
    - port: 8000 # Exposed Port
      targetPort: 3000 # Application Port
      protocol: TCP
  selector:
    app.kubernetes.io/name: roku-remote
