apiVersion: v1
kind: Service
metadata:
  name: svc-sample-js-app
  labels:
    chapter: services
spec:
  # ipFamilyPolicy: PreferDualStack
  # ipFamilies:
  # - IPv4
  # - IPv6
  # type: NodePort
  type: LoadBalancer
  ports:
    - port: 8080 # Exposed Port
      # nodePort: 30001
      targetPort: 3000 # Application Port
      protocol: TCP
  selector:
    chapter: services
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-sample-js-app
spec:
  replicas: 2
  selector:
    matchLabels:
      chapter: services
  template:
    metadata:
      labels:
        chapter: services
    spec:
      containers:
        - name: sample-js-app
          image: gregorymichaelroman/sample-app:latest
          ports:
            - containerPort: 3000
